% This is used to set the path to source images
%
% Please change the path in line 16 to your own path before running
%
% Author:Xingchen Zhang
% Contact: xingchen.zhang@imperial.ac.uk
%
% If you use this code, please site the following paper:
%
% Zhang, Xingchen. "Benchmarking and comparing multi-exposure image fusion algorithms." 
% Information Fusion (2021).

function imgs=configImgs_MEFB

    path = 'C:\data\MEFB\';

    imgs = {struct('name', '1','path',path,'ext','png'),...
struct('name', '2','path',path,'ext','png'),...
struct('name', '3','path',path,'ext','png'),...
struct('name', '4','path',path,'ext','png'),...
struct('name', '5','path',path,'ext','png'),...
struct('name', '6','path',path,'ext','png'),...
struct('name', '7','path',path,'ext','png'),...
struct('name', '8','path',path,'ext','png'),...
struct('name', '9','path',path,'ext','png'),...
struct('name', '10','path',path,'ext','png'),...
struct('name', '11','path',path,'ext','png'),...
struct('name', '12','path',path,'ext','png'),...
struct('name', '13','path',path,'ext','png'),...
struct('name', '14','path',path,'ext','png'),...
struct('name', '15','path',path,'ext','png'),...
struct('name', '16','path',path,'ext','png'),...
struct('name', '17','path',path,'ext','png'),...
struct('name', '18','path',path,'ext','png'),...
struct('name', '19','path',path,'ext','png'),...
struct('name', '21','path',path,'ext','png'),...
struct('name', '22','path',path,'ext','png'),...
struct('name', '23','path',path,'ext','png'),...
struct('name', '24','path',path,'ext','png'),...
struct('name', '25','path',path,'ext','png'),...
struct('name', '26','path',path,'ext','png'),...
struct('name', '27','path',path,'ext','png'),...
struct('name', '28','path',path,'ext','png'),...
struct('name', '29','path',path,'ext','png'),...
struct('name', '30','path',path,'ext','png'),...
struct('name', '32','path',path,'ext','png'),...
struct('name', '33','path',path,'ext','png'),...
struct('name', '34','path',path,'ext','png'),...
struct('name', '35','path',path,'ext','png'),...
struct('name', '36','path',path,'ext','png'),...
struct('name', '37','path',path,'ext','png'),...
struct('name', '38','path',path,'ext','png'),...
struct('name', '39','path',path,'ext','png'),...
struct('name', '41','path',path,'ext','png'),...
struct('name', '43','path',path,'ext','png'),...
struct('name', '44','path',path,'ext','png'),...
struct('name', '46','path',path,'ext','png'),...
struct('name', '47','path',path,'ext','png'),...
struct('name', '48','path',path,'ext','png'),...
struct('name', '49','path',path,'ext','png'),...
struct('name', '50','path',path,'ext','png'),...
struct('name', '51','path',path,'ext','png'),...
struct('name', '52','path',path,'ext','png'),...
struct('name', '53','path',path,'ext','png'),...
struct('name', '54','path',path,'ext','png'),...
struct('name', '55','path',path,'ext','png'),...
struct('name', '56','path',path,'ext','png'),...
struct('name', '57','path',path,'ext','png'),...
struct('name', '58','path',path,'ext','png'),...
struct('name', '59','path',path,'ext','png'),...
struct('name', '60','path',path,'ext','png'),...
struct('name', '61','path',path,'ext','png'),...
struct('name', '63','path',path,'ext','png'),...
struct('name', '64','path',path,'ext','png'),...
struct('name', '65','path',path,'ext','png'),...
struct('name', '66','path',path,'ext','png'),...
struct('name', '67','path',path,'ext','png'),...
struct('name', '69','path',path,'ext','png'),...
struct('name', '70','path',path,'ext','png'),...
struct('name', '71','path',path,'ext','png'),...
struct('name', '72','path',path,'ext','png'),...
struct('name', '73','path',path,'ext','png'),...
struct('name', '74','path',path,'ext','png'),...
struct('name', '75','path',path,'ext','png'),...
struct('name', '76','path',path,'ext','png'),...
struct('name', '77','path',path,'ext','png'),...
struct('name', '78','path',path,'ext','png'),...
struct('name', '79','path',path,'ext','png'),...
struct('name', '80','path',path,'ext','png'),...
struct('name', '81','path',path,'ext','png'),...
struct('name', '82','path',path,'ext','png'),...
struct('name', '83','path',path,'ext','png'),...
struct('name', '84','path',path,'ext','png'),...
struct('name', '85','path',path,'ext','png'),...
struct('name', '86','path',path,'ext','png'),...
struct('name', '87','path',path,'ext','png'),...
struct('name', '88','path',path,'ext','png'),...
struct('name', '89','path',path,'ext','png'),...
struct('name', '90','path',path,'ext','png'),...
struct('name', '91','path',path,'ext','png'),...
struct('name', '92','path',path,'ext','png'),...
struct('name', '94','path',path,'ext','png'),...
struct('name', '95','path',path,'ext','png'),...
struct('name', '96','path',path,'ext','png'),...
struct('name', '97','path',path,'ext','png'),...
struct('name', '98','path',path,'ext','png'),...
struct('name', '99','path',path,'ext','png'),...
struct('name', '100','path',path,'ext','png'),...
% struct('name', '20','path',path,'ext','png'),...
% struct('name', '93','path',path,'ext','png'),...
% struct('name', '68','path',path,'ext','png'),...
% struct('name', '62','path',path,'ext','png'),...
% struct('name', '45','path',path,'ext','png'),...
% struct('name', '42','path',path,'ext','png'),...
% struct('name', '40','path',path,'ext','png'),...
% struct('name', '31','path',path,'ext','png'),...

        };

end
