% This is used to set the path to source images
%
% Please change the path in line 16 to your own path before running
%
% Author:Xingchen Zhang
% Contact: xingchen.zhang@imperial.ac.uk
%
% If you use this code, please site the following paper:
%
% Zhang, Xingchen. "Benchmarking and comparing multi-exposure image fusion algorithms." 
% Information Fusion (2021).

function imgs=configImgs_SICE

    path = 'C:\data\SICE\test_512\';

    imgs = {struct('name', '1','path',path,'ext','png'),...
struct('name', '2','path',path,'ext','png'),...
struct('name', '3','path',path,'ext','png'),...
struct('name', '4','path',path,'ext','png'),...
struct('name', '5','path',path,'ext','png'),...
struct('name', '6','path',path,'ext','png'),...
struct('name', '7','path',path,'ext','png'),...
struct('name', '8','path',path,'ext','png'),...
struct('name', '9','path',path,'ext','png'),...
struct('name', '10','path',path,'ext','png'),...
struct('name', '11','path',path,'ext','png'),...
struct('name', '12','path',path,'ext','png'),...
struct('name', '13','path',path,'ext','png'),...
struct('name', '14','path',path,'ext','png'),...
struct('name', '15','path',path,'ext','png'),...
struct('name', '16','path',path,'ext','png'),...
struct('name', '17','path',path,'ext','png'),...
struct('name', '18','path',path,'ext','png'),...
struct('name', '19','path',path,'ext','png'),...
struct('name', '20','path',path,'ext','png'),...
struct('name', '21','path',path,'ext','png'),...
struct('name', '22','path',path,'ext','png'),...
struct('name', '23','path',path,'ext','png'),...
struct('name', '24','path',path,'ext','png'),...
struct('name', '25','path',path,'ext','png'),...
struct('name', '26','path',path,'ext','png'),...
struct('name', '27','path',path,'ext','png'),...
struct('name', '28','path',path,'ext','png'),...
struct('name', '29','path',path,'ext','png'),...
struct('name', '30','path',path,'ext','png'),...
        };

end
